### ISSUE TITLE
live view missing

### ISSUE THREAD

**Issue by serveradmin09** [fradaloisio/cloudedge-ha#1]
sadly, there is no live view for none of my cameras

<img width="585" height="184" alt="Image" src="https://github.com/user-attachments/assets/b4823069-12c2-465e-9e59-d28246263ed8" />

also, icon files seem to be inaccessable:

<img width="271" height="247" alt="Image" src="https://github.com/user-attachments/assets/a12ef38b-931c-44ba-b142-cf9b7a604e96" />

**Comment by censiir** [comment]
@marionetti92 @serveradmin09 you can check my repository on https://github.com/censiir/cloudedge-client that has a Python script that's able to stream from CloudEdge.

@fradaloisio you can also merge my changes there into here if you want

**Comment by fradaloisio** [comment]
Wow 😍 thanks a lot, @censiir! 
I have already implemented video streaming, but it only works with European accounts. Other regions, such as the US and Australia, are not working. Does your library support all of them?

Also, I noticed in the README that your library includes many features I haven't implemented yet. Would it be possible for me to use or adapt some of them? I saw that the license says "Research / educational use."

**Comment by Zer0ProSac** [comment]
Hello Francesco,

im from Germany can you publish the Liveview version?
Or can i test it on a Beta version?

Would really nice when for German Liveview works.

**Comment by censiir** [comment]
@fradaloisio you are free to use and implement whatever you'd like under the GPLv3. If this license doesn't work for you, contact me at ubayds04@gmail.com.

"Other regions, such as the US and Australia, are not working. Does your library support all of them?"

I was able to get it working in the US where I am based. If you could expand on what isn't working, that would be helpful.

<img width="1466" height="819" alt="Image" src="https://github.com/user-attachments/assets/e55e848b-daf9-47c9-b8f3-0e777295fa09" />

**Comment by censiir** [comment]
@fradaloisio oh sorry, I totally misunderstood your question!

Yes, my library does work with any region (it is agnostic), but you must manually provide parameters such as DID, init string, and password.

**Comment by censiir** [comment]
Also important to note that it does not support restrictive NAT (relay mode), as I felt the biggest use of this was for HA/Scrypted.

**Comment by ajvlc** [comment]
@fradaloisio Does your integration provide the DID, init string, and password?

**Comment by xDAVIDx93** [comment]
Can’t wait to get live view here in Australia! Well done devs 👍

**Comment by ajvlc** [comment]
Hello! Are you going to implement live video?

**Comment by fradaloisio** [comment]
Hello, I've implemented a first version of the streming. Please upgrade to the latest version.
Once you click on the camera preview, wait some seconds to see the streaming. For now is not good as in the app.

**Comment by ajvlc** [comment]
Good morning, I have updated and already tested it.
The video loads quite fast.
But is it possible that it doesn't have audio?
Thank you very much, great job.

**Comment by ajvlc** [comment]
Good afternoon, when you open the video and finish watching it, it remains permanently transmitting and the battery drains.

The camera doesn't go back to sleep.

**Comment by Speedpoint1** [comment]
Confirming this still happens on the latest release (v1.3.0). Camera is a generic CTSC-5S clone. Log shows:

P2P signaling attempt failed via 47.254.142.96:18843: timed out
Live stream for <serial> failed 4 times in a row; giving up until a new stream request

All other entities (motion, connection status, etc.) work fine - only the P2P live view times out.

Before reporting I ruled out anything on my own network. Exposed Host already forwards all inbound traffic to the HA host, so no double-NAT blocking is involved. No firewall/IDS is blocking the endpoint either (checked flow/traffic logs, nothing dropped). And the same account's official app streams fine from the same LAN AND from mobile data, i.e. a completely different network path, so it's not a NAT/network issue on my end.

Given the April discussion about streaming working for European accounts but not US/Australia: my account logs in via the web-us.cloudedge360.com portal, even though I'm in Germany and the camera's stream_openapi_host reported by the integration is openapi-euce.mearicloud.com (looks EU-based). Not sure if that portal/region mismatch is relevant, but flagging it in case it helps narrow down the region-dependent P2P behavior mentioned earlier in this thread.

Happy to provide more logs if useful.
